project:
  type: website
  output-dir: docs

website:
  title: "DSAN 5450"
  favicon: favicon.png
  sidebar:
    id: mainnav
    title: "DSAN 5450: Data Ethics and Policy"
    contents:
      - text: "<i class='bi bi-house pe-1'></i> Home"
        href: index.qmd
      - text: "Syllabus"
        href: syllabus.qmd
      - text: "Writeups"
        href: writeups/index.qmd
      - text: "Recordings"
        href: recordings/index.qmd
      - "---"
      - text: "Week 1: Jan 17"
        href: "w01/index.qmd"
      - text: "Week 2: Jan 24"
        href: "w02/index.qmd"
      - text: "Week 3: Jan 30"
        href: "w03/index.qmd"
      - text: "Week 4: Feb 6"
        href: "w04/index.qmd"
      - text: "Week 5: Feb 13"
        href: "w05/index.qmd"
      - text: "Week 6: Feb 20"
        href: "w06/index.qmd"
      - text: "Week 7: Feb 27"
        href: "w07/index.qmd"
      - "---"
      - text: "Anonymous Suggestions<i class='bi bi-box-arrow-up-right ps-1'></i>"
        href: "https://forms.gle/LLQsiwGy5kkH5n3PA"
        target: "_blank"

format:
  html:
    theme: default
    css: styles.css
    toc: true
    include-in-header:
      text: "<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js' integrity='sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==' crossorigin='anonymous' referrerpolicy='no-referrer'></script><script src='/jjcustom.js'></script>"




