project:
  type: website
  output-dir: docs

website:
  title: "dsan5450"
  sidebar:
    title: "DSAN 5450<br>3:30-6:00pm, Walsh 498"
    contents:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



