project:
  type: website
  output-dir: docs

website:
  title: "DSAN 5450"
  sidebar:
    title: "DSAN 5450"
    contents:
      - text: "<i class='bi bi-house pe-1'></i> Home"
        href: index.qmd
      - text: "Syllabus"
        href: syllabus.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



