project:
  type: website
  output-dir: docs

website:
  title: "DSAN 5450"
  favicon: favicon.png
  sidebar:
    title: "DSAN 5450"
    contents:
      - text: "<i class='bi bi-house pe-1'></i> Home"
        href: index.qmd
      - text: "Syllabus"
        href: syllabus.qmd
      - "---"
      - text: "Week 01"
        href: "w01/index.qmd"

format:
  html:
    theme: default
    css: styles.css
    toc: true
    include-in-header:
      text: "<script src='/jjcustom.js'></script><script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js' integrity='sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==' crossorigin='anonymous' referrerpolicy='no-referrer'></script>"




