---
title: "Assignment Point Distributions"
subtitle: "DSAN 5450: Data Ethics and Policy"
sidebar: mainnav
format:
  html:
    df-print: kable
---

Use the **tabs below** to view the point distributions for different assignments.

The distributions are imported from Google Sheets mainly for transparency: so that you can see exactly how totals are computed as a sum of the individual points allocated for each test!

```{r}
#| label: points-table-fn
#| warning: false
#| echo: false
library(tidyverse) |> suppressPackageStartupMessages()
gen_points_table <- function(hw_url) {
  hw_df <- read_csv(hw_url)
  # print(colnames(hw_df))
  hw_df <- hw_df |> select(part, qid, points, part_total)
  hw_df <- hw_df |> drop_na(points)
  hw_df$points <- as.character(hw_df$points)
  hw_df$part_total <- as.character(hw_df$part_total)
  hw_df <- hw_df |> mutate(
    part = replace_na(part, ""),
    part_total = replace_na(part_total, ""),
    qid = replace_na(qid, ""),
    # test_type = replace_na(test_type, "")
  )
  return(hw_df)
}
```

::: {.panel-tabset}

## HW1

<div style="height: 400px !important; max-height: 400px !important; overflow-y: scroll !important;">

```{r}
#| label: hw1-points-table
#| warning: false
#| echo: false
# hw1_url <- "https://docs.google.com/spreadsheets/d/e/2PACX-1vStpSHtuJy38apEKdY7akAsUTo1ovM2AR5VQ7AuVUpK4kbbxOSaaWeChP-zg2VKfGcvdctPTIxVy4NG/pub?output=csv"
hw1_url <- "https://docs.google.com/spreadsheets/d/e/2PACX-1vRgzXNVDP9K_vqLy5uAVKQVY_gLbrG7nVpB99wPfSV8I8r_p_M2jGF3I_XWSRd3Q66ywIggcxTHPe0m/pub?output=csv"
gen_points_table(hw1_url)
```

</div>

:::
