---
title: "Syllabus"
---

**Welcome to DSAN 5450: Data Ethics and Policy!**


## Course Description

This graduate-level course will train students to navigate the landscape of ethical issues which arise at each step of the data science process, with an eye towards developing policy recommendations for governments and organizations seeking expert advice on how to tackle these issues from a regulatory perspective. Students will explore and critically evaluate a range of data-related issues in contemporary society, such as responsible data collection, algorithmic bias, privacy, transparency, accountability, democratic participation in data usage and data-driven decisions, and the ethical implications of emerging technologies like artificial intelligence and machine learning (self-driving cars, ChatGPT, crowd-sourced training data, etc.).

Beginning with a set of historical case studies—instances in which scientists, engineers, and policymakers have been forced to re-evaluate their ethical intuitions in light of technological developments (nuclear power, use of social media platforms to organize protests and influence political outcomes, deployment of facial recognition software and predictive AI by police and military forces)—the course then introduces a set of general ethical frameworks (consequentialism, deontological ethics, and virtue ethics), challenging students to consider their relative strengths and weaknesses for addressing modern technological-ethical dilemmas faced by businesses, healthcare organizations, governments, and academic institutions. After a final portion of the course linking these ethical frameworks with practical regulatory and policy considerations, students will write and present a policy whitepaper analyzing a data-ethical issue of particular interest to them, integrating ethical perspectives, regulatory principles, and domain knowledge into a recommendation of best practices for the relevant agency, firm, or institution.

The course will thus equip students with a robust ethical "toolbox" for conscientiously gathering, interpreting, and extracting meaning from data throughout their careers as data scientists, while respecting privacy, fairness, transparency, democratic accountability, and other social concerns. *Prerequisites: None. 3 credits*.

## Course Overview

The course revolves around three "pillars", which we'll examine individually before bringing them together for your final projects at the end of the class.

### Data Science

A portion of the course will focus on introductions to cutting-edge technologies like self-driving cars, ChatGPT, facial detection algorithms, and various applications of AI to police and military technologies. For this portion, we'll draw fairly often from the contents of the following books:

* Catherine D'Ignazio and Lauren F. Klein (2020). <i><a href='https://data-feminism.mitpress.mit.edu/' target='_blank'>Data Feminism</a></i>. Cambridge, MA: MIT Press. [Free, open-source!]
* Cathy O'Neil (2016). <i><a href='https://en.wikipedia.org/wiki/Weapons_of_Math_Destruction' target='_blank'>Weapons of Math Destruction</a></i>. New York, NY: Crown Books.

Since there are plenty of in-depth resources available to you (e.g., other Georgetown courses!) for learning the *technical details* of these technologies, our goal in this course will be to learn just the particular *aspects* of each technology which are most relevant to the ethical and policy issues they present.

For example, we will look at Neural Netwok-based Machine Learning algorithms, but we will focus specifically on how the **performance** of these algorithms on a given task depends crucially on the existence of effective **training data** for that task. The breakthroughs in Artificial Intelligence which have had an immense impact on society over the past few decades, for example, have **not** come about because of new algorithms (neural networks, for example, have been around since the 1950s). Rather, they have come about because of the massive, exponential increase in the amount of **data** available to **train** these already-existing algorithms: for example, data scraped from across the entire web, or from millions of scanned books, or from Wikipedia's massive collection of articles. This means, therefore, that these algorithms simply **encode** pre-existing human biases into algorithmically-derived "rules", thus motivating the next pillar of the course: Ethics!

### Ethics

For the ethics-focused portion of the course, we'll be reading selections from the following textbook:

* Lewis Vaughn and Louis P. Pojman (2021). <i><a href='https://global.oup.com/ushe/product/the-moral-life-9780197610060?cc=us&lang=en&' target='_blank'>The Moral Life: An Introductory Reader in Ethics and Literature</a></i>. Oxford, UK: Oxford University Press. [<a href='https://www.dropbox.com/scl/fi/edx5t4xedli9pcfxm3330/Louis-P.-Pojman-The-Moral-Life_-An-Introductory-Reader-in-Ethics-and-Literature.pdf?rlkey=6pwuvdfed6m8mzp3d0l5rsajv&dl=1' target='_blank'>PDF</a>]

From the vast array of readings contained in this collection, we'll look at both "standard" ethical readings from e.g. Jeremy Bentham and Immanuel Kant plus readings from literary sources like Ursula Le Guin, Ambrose Bierce, Jesus' Sermon on the Mount, and Buddha's Four Noble Truths.

### Public Policy

For the final piece of the course we will take the **technological developments** discussed the first portion, analyze them using the **ethical frameworks** discussed in the second portion, and come to **conclusions** as to what types of things lawmakers, governments, and civil society organizations (NGOs, for example, and Think Tanks) can do **in practice** to address the ethical issues raised by these technologies. This means that, specifically, the recommended final project for the course will be a **Policy Whitepaper**, where you will choose a particular institution and make a **recommendation** to them in terms of how they can use their power (for example, the power to pass laws) to most effectively address an ethical issue that you believe is important.

For this portion of the class we'll have to draw on a wide range of different readings, depending on what particular subdomains of public policy are most interesting to you all, but as a general textbook on ethics in data science which does focus a good amount on **policy** specifically, we will look at:

* Anne L. Washington (2023). <i><a href=' https://annewashington.com/book-ethical-data-science-prediction-in-the-public-interest/' target='_blank'>Ethical Data Science: Prediction in the Public Interest</a></i>. New York, NY: Oxford University Press.

Now that you have an overview of the trajectory of the course, the following section contains the particulars of what we'll be reading and working on each week!

## Schedule

The following is a rough map of what we will work through together throughout the semester; given that **everyone learns at a different pace**, my aim is to leave us with a good amount of **flexibility** in terms of how much time we spend on each topic: if I find that it takes me longer than a week to convey a certain topic in sufficient depth, for example, then I view it as a strength rather than a weakness of the course that we can then rearrange the calendar below by adding an extra week on that particular topic! Similarly, if it seems like I am spending too much time on a topic, to the point that students seem bored or impatient to move onto the next topic, we can move a topic intended for the next week to the current week!

```{=html}
<table>
<thead>
<tr>
    <th>Unit</th>
    <th>Week</th>
    <th>Date</th>
    <th>Topic</th>
</tr>
</thead>
<tbody>
<tr>
    <td><span data-qmd="**Unit 1**: Data-Scientific Issues"></span></td>
    <td>1</td>
    <td><span data-qmd="Jan 10 (**Wednesday**)"></span></td>
    <td>Intro to the Course</td>
</tr>
<tr>
    <td></td>
    <td></td>
    <td>Jan 15</td>
    <td>No Class (Martin Luther King, Jr. Day)</td>
</tr>
<tr>
    <td></td>
    <td>2</td>
    <td>Jan 22</td>
    <td>Machine Learning and Training Data</td>
</tr>
<tr>
    <td></td>
    <td>3</td>
    <td>Jan 29</td>
    <td>Applications Part 1: Self-Driving Cars, Facial Recognition, and ChatGPT</td>
</tr>
<tr>
    <td></td>
    <td>4</td>
    <td>Feb 5</td>
    <td>Applications Part 2: Police and Military Applications of AI</td>
</tr>
<tr>
    <td><span data-qmd="**Unit 2**: Ethical Frameworks"></span></td>
    <td>5</td>
    <td>Feb 12</td>
    <td>Consequentialism</td>
</tr>
<tr>
    <td></td>
    <td>6</td>
    <td>Feb 19</td>
    <td>Deontological Ethics</td>
</tr>
<tr>
    <td></td>
    <td>7</td>
    <td>Feb 26</td>
    <td>Virtue Ethics</td>
</tr>
<tr>
    <td></td>
    <td></td>
    <td>Mar 4</td>
    <td>No Class (Spring Break)</td>
</tr>
<tr>
    <td></td>
    <td>8</td>
    <td>Mar 11</td>
    <td>Applying Our Ethical Frameworks to Self-Driving Cars, Facial Recognition, and ChatGPT</td>
</tr>
<tr>
    <td></td>
    <td>9</td>
    <td>Mar 18</td>
    <td>Applying Our Ethical Frameworks to Police and Military Applications of AI</td>
</tr>
<tr>
    <td><span data-qmd="**Unit 3**: Public Policy"></span></td>
    <td>10</td>
    <td>Mar 25</td>
    <td>Intro to Public Policy</td>
</tr>
<tr>
    <td></td>
    <td></td>
    <td>Apr 1</td>
    <td>No Class (Easter Break)</td>
</tr>
<tr>
    <td></td>
    <td>11</td>
    <td>Apr 8</td>
    <td>Authoring Policy Whitepapers</td>
</tr>
<tr>
    <td></td>
    <td>12</td>
    <td>Apr 15</td>
    <td>Applications: Public Policy and Climate Justice</td>
</tr>
<tr>
    <td></td>
    <td>13</td>
    <td>Apr 22</td>
    <td>Applications: Race, Class, Gender, Sexuality, and Disability (Data Feminism)</td>
</tr>
<tr>
    <td></td>
    <td>14</td>
    <td>Apr 29</td>
    <td>Applications: Public Policy and International Law</td>
</tr>
</tbody>
</table>
```