---
title: "Policy Proposals from *Power and Progress*"
author: "Jeff Jacobs"
sidebar: mainnav
date: 2026-04-08
bibliography: "../../_DSAN5450.bib"
csl: "../../chicago-17-no-url.csl"
relevance: "Final Project"
categories:
  - "Extra Writeups"
format:
  html:
    df-print: kable
    html-math-method: mathjax
    toc: true
---

The following excerpt from Chapter 11 of @acemoglu_power_2023, titled "Redirecting Technology", contains a series of policy proposals that you can use as inspiration for your final policy whitepapers!

Several of them have been discussed in class (especially "Data Ownership and Data Externalities"), so you may want to focus on those, but that's just a recommendation! Any topic within this excerpt that seems interesting to you is worth pursuing 😊

---

## The Progressive Movement (pg. 388)

The Progressive Movement provides a historical perspective on the three prongs of a critical formula necessary for escaping our current predicament.

The first is altering the narrative and changing norms. The Progressives enabled individual Americans to have an informed view about troubles in the economy and society—rather than just accepting the line coming from lawmakers, business tycoons, and the yellow journalists allied with them. For example, Tarbell never presented herself as a political candidate or even committed to one cause. Instead, she honed her craft of investigative journalism to expose the main facts about Standard Oil and its boss, Rockefeller. Critically, Progressives transformed what was viewed as acceptable for companies to do and what ordinary citizens thought they could do about injustices.

The second is cultivating countervailing powers. Building on the change in the narrative and social norms, Progressives helped organize people into a broad movement that could oppose robber barons and push politicians to reform, including via labor unions.

The third prong is policy solutions, which Progressives articulated based on the new narrative, research, and expertise.

## Redirecting Technological Change (pgs. 388)

Although the challenges facing us today are digital and global, the lessons of the Progressive Era are still relevant. The contemporary environmental movement confronting the existential threat of climate change demonstrates that the formula's three prongs can work to redirect technological change today. Despite the continued reliance of most large energy companies on fossil fuels and  the failure of most policy makers to act, there have been remark  able advances in renewable energy technologies.

Fossil-fuel emissions are first and foremost a technology problem. Industrialization was built on fossil-fuel energy, and technological investments since the middle of the eighteenth century have focused on improving and expanding these conventional energy sources. As early as the 1980s, it was clear that fossil-fuel emissions could not be reduced to levels that would prevent continuous warming of the climate by just relying on small tweaks to  coal and oil production and consumption. New sources of energy were needed, which meant a major redirection of technology. Little of this happened for several decades. As late as the mid-2000s, solar energy was more than twenty times as expensive as energy from fossil fuels. For wind, the factor was about ten. Although hydroelectric energy was already cheaper in the 1990s, capacity was limited.

Today, solar, wind, and hydro energy are cheaper to operate than fossil-fuel power stations. For example, the International Renewable Energy Agency estimates that fossil fuels cost between $50 and $150 per 100 kWh (kilowatt hours), photovoltaic solar power costs between $40 and $54, and onshore wind power comes in at less than $40. Although there are some activities for which  renewables cannot be used effectively (such as jet fuel) and there are important storage challenges, most of the electric grid of the world could be powered by renewables, when policy makers decide to move in that direction.

How did this impressive achievement take place? First came the change in narrative on climate. Rachel Carson's *Silent Spring*, published in 1962, was one of the first steps. Several organizations, most prominently Greenpeace, were campaigning strongly to protect the environment by the 1970s. Greenpeace initiated a program on global warming in the early 1990s, attempting to be a counterweight against the tactics used by big oil companies to hide the environmental damages that fossil fuels were causing.

The 2006 documentary film *An Inconvenient Truth*, focusing on former vice president and presidential candidate Al Gore's efforts to inform the public about global warming, played a major role. The movie was watched by millions all over the world.

Around the same time, new organizations focused on climate change, such as 350.org, were launched. As 350.org's founder, Bill McKibben, put it, the environment was the main issue, and all else paled in comparison: "In 50 years, no one will care about the fiscal cliff or the Euro crisis. They'll just ask, 'So the Arctic melted, and then what did you do?'"

The change in narrative coalesced into a more organized political movement with Green parties, which made global warming the centerpiece of their agenda. The German Green Party became a powerful electoral force and entered the government a number of times. Environmentalists played a similar role in other Western European nations as well. A show of force by the environmental movement came during a series of climate strikes in September 2019, with protests and walkouts in schools and workplaces across 4,500 cities around the globe.

Two major consequences followed from the second prong. These movements put pressure on the corporate sector. As the population in many Western nations became informed about the dangers of climate change, they demanded cleaner products, such as electric cars and renewable energy, and employees at many large corporations insisted on reductions in their companies' carbon footprint. Equally, they pushed (some) policy makers into taking global warming seriously.

These developments activated the third prong, technical and policy solutions. Economic and environmental analyses identified three critical levers for combating climate change: a carbon tax to reduce fossil-fuel emissions, support for innovation and research in renewable energy and other clean technologies, and regulation against the worst polluting technologies.

Although carbon taxes face stiff opposition in many countries, not least in the United States, Britain, and Australia, they have been introduced in several European countries. The levels of carbon tax adopted around the world are still inadequate given global warming trends, but some nations are gradually increasing this tax. The Swedish rate now stands above $120 per metric ton of carbon dioxide, amounting to a significant increase in the price of coal-powered energy.

A carbon tax is a powerful tool to curb carbon emissions.  Because it reduces the profitability of fossil-fuel production, it can spur investment in alternative energy sources. But at the current levels, it makes only a small dent in the profits of fossil-fuel companies and would not lead to a major redirection of technology. Much more potent are schemes that directly incentivize innovations and investment in clean energy. The US government  recently provided annual tax credits of more than $10 billion for renewables and almost $3 billion for improving energy efficiency. Some funds are also directly targeted at new technologies—for example, under the auspices of the National Renewable Energy Laboratory, NASA, and the Department of Defense. Subsidies to renewables research have been even more generous in Germany and the Nordic countries.

Regulations, such as emissions standards by the state of California, first adopted in 2002, played a role in directly discouraging the most inefficient uses of fossil fuel—for instance, by forcing older models of vehicles that have much higher gas consumption off the road. These regulations have also encouraged further research in electric cars.

The three policy levers (carbon taxes, research subsidies, and regulations), together with pressure from consumers and civil society, led to a boost both in innovations in renewables and much larger levels of production of solar panels and wind energy. The basic technology that generates energy through the photovoltaic effect, by using the sun's photons, has been known since the late nineteenth century, and viable solar panels were first produced in the 1950s in the Bell Labs. Important breakthroughs followed, starting in the 2000s, as the number of patents related to clean energy increased dramatically in the United States, France, Germany, and Britain. As production expanded, the costs of solar panels plummeted. As a result of these rapid improvements, renewables already make up over 20 percent of total energy consumption in Europe, although the United States is lagging behind.

Remarkably, China followed the European and American  redirection of this technology. The country began producing solar panels in response to growing demand in Europe, especially Germany, in the late 1990s, following European climate-mitigation policies. Motivated by a desire to play a leading role in this sector and also to deal with the country's own severe pollution problem, the Chinese government provided generous subsidies and loans to producers, rapidly boosting productive capacity. Costs  of photovoltaic panels and other solar equipment started declining thanks to "learning by doing" (meaning that as volumes rose, firms became better and better at producing cost-effective and energy-efficient solar panels). Chinese producers introduced new machinery and improved techniques for cutting polysilicon wafers more thinly, enabling them to produce more solar cells from the same amount of material, reducing costs and increasing production. The country is now the largest producer of solar panels and  polysilicon in the world (even if many of the solar panel factories are powered by electricity generated from coal). According to the Chinese government's statistics, renewable energy accounted for about 29 percent of electricity consumption in 2020.

Of course, success to date should not be exaggerated. There are still many areas, such as cost-effective energy storage, in which breakthroughs are needed, and several sectors, such as air transport and agriculture, have not reduced their carbon emissions. Emissions in the developing world, including in China and India, are still growing, despite advances in renewable technology. There  is little prospect for a global carbon tax that can powerfully reduce consumption in the immediate future.

Nevertheless, from the point of view of the challenge of digital technologies, there is much we can learn from how technology is being redirected in the energy sector. The same combination—altering the narrative, building countervailing powers, and developing and implementing specific policies to deal with the most important issues—can work in redirecting digital technology.

## Remaking Digital Technologies (pg. 392)

Our current problems are rooted in the enormous economic,  political, and social power of corporations, especially in the tech industry. The concentrated **power** of business undercuts shared prosperity because it limits the **sharing of gains** from technological change. But its most pernicious impact is via the direction of technology, which is moving excessively toward **automation**, **surveillance**, **data collection**, and **advertising**. To regain shared prosperity, we must redirect technology, and this means activating a version of the same approach that worked more than a century ago for the Progressives.

This can start only by altering the narrative and the norms. The necessary steps are truly fundamental. Society and its powerful gatekeepers need to stop being mesmerized by tech billionaires and their agenda. Debates on new technology ought to center not just on the brilliance of new products and algorithms but also on whether they are working for the people or against the people. **Whether** digital technologies **should**^[Notice the *normative* content here, indicated by the use of "should"!] be used for automating work and empowering large companies and nondemocratic governments must not be the **sole decision** of a handful of entrepreneurs and engineers. One **does not need to be an AI expert** to have a say about the direction of progress and the future of our society forged by these technologies^[Here, think of the takeaway from the "reverse-engineering" of values you carried out for PROGRESA in HW4: Once "society" decides how much they value consumption vs. health vs. education (granted, this aggregation of individual $\leadsto$ social preferences is one of the main Hard Problems in this course!), you can use the methods from that homework to determine whose interests may be favored relative to others.]. One does not need to be a tech investor or venture capitalist to hold tech entrepreneurs and  engineers accountable for what their inventions do.

Choices over the direction of technology should be part of the criteria that investors use for evaluating companies and their effects. Large investors can demand transparency on whether new technologies will automate work or create new tasks, whether they will monitor or empower workers, and how they will affect political discourse and other social outcomes. These are not decisions investors should care about only because of the profits they generate. A two-tiered society with a small elite and a dwindling  middle class is not a foundation for prosperity or democracy. Nevertheless, it is possible to make digital technologies useful to humans and boost productivity so that investing in technologies that help humans can also be good business.

As with the Progressive Era reforms and redirection in the energy sector, a new narrative is critical for building countervailing powers in the digital age. Such a narrative and public pressure can trigger more responsible behavior among some decision makers. For example, we saw in Chapter 8 that managers with business-school educations tend to reduce wages and cut labor costs, presumably because of the lingering influence of the Friedman doctrine—the idea that the only purpose and responsibility of business is to make profits. A powerful new narrative about shared prosperity can be a counterweight, influencing the priorities of some managers and even swaying the prevailing paradigm in business schools. Equally, it can help reshape the thinking of tens of thousands of bright young people wishing to work in the tech sector—even if it is unlikely to have much impact on tech tycoons.

More fundamentally, these efforts must formulate and support specific policies to rechart the course of technology. As we explained in Chapter 9, digital technologies can complement humans by:

* improving the productivity of workers in their current jobs
* creating new tasks with the help of machine intelligence augmenting human capabilities
* providing better, more usable information for human decision making
* building new platforms that bring together people with different skills and needs

For example, digital and AI technologies can increase effectiveness of classroom instruction by providing new tools and better information to teachers. They can enable personalized instruction by identifying in real time areas of difficulty or strength for each student, thus generating a plethora of new, productive tasks for  teachers. They can also build platforms that bring teachers and teaching resources more effectively together. Similar avenues are open in health care, entertainment, and production work, as we have already discussed.

An approach that complements workers, rather than sidelining and attempting to eliminate them, is more likely when diverse human skills, based on the situational and social aspects of human cognition, are recognized. Yet such diverse objectives for technological change necessitate a plurality of innovation strategies, and  they become less likely to be realized when a few tech firms dominate the future of technology.

Diverse innovation strategies are also important because automation is not harmful in and of itself. Technologies that replace tasks performed by people with machines and algorithms are as old as industry itself, and they will continue to be part of our future. Similarly, data collection is not bad per se, but it becomes inconsistent both with shared prosperity and democratic governance when it is centralized in the hands of **unaccountable** companies and governments that use these data to disempower people. The problem is an unbalanced portfolio of innovations that excessively prioritize automation and surveillance, failing to create new tasks and opportunities for workers. Redirecting technology need not involve the blocking of automation or banning data collection; it can instead encourage the development of technologies that complement and help human capabilities.

Society and government must work together to achieve this  objective. Pressure from civil society, as in the case of successful major reforms of the past, is key. Government regulation and incentives are critical too, as they were in the case of energy. However, the government cannot be the nerve center of innovation, and bureaucrats are not going to design algorithms or come up with new products. What is needed is the right institutional framework and incentives shaped by government policies, bolstered by a constructive narrative, to induce the private sector to move away from excessive automation and surveillance, and  toward more worker-friendly technologies.

A central question is whether efforts toward redirecting technology in the West would be of any use if China continues to pursue automation and surveillance. The answer is likely yes. China is still a follower in most frontier technologies, and redirection efforts in the United States and Europe will have a major impact on global technology. As in the case of energy innovations, a serious redirection in the West can powerfully influence Chinese investments as well.

How to foster countervailing powers that influence the path of future technologies and incentivize socially beneficial technological change is our focus in the rest of this chapter.

## Remaking Countervailing Powers (pg. 396)

We cannot redirect technology without building new countervailing powers. And we cannot build countervailing powers without relying on civil-society organizations that bring people together around shared issues and cultivate norms of self-governance and political action.

### Worker Organization

Labor unions have been a mainstay of countervailing powers since the beginning of the industrial age. They are a key vehicle for supporting the sharing of productivity gains between employers and workers. In workplaces where labor  has a voice (either in the form of unions or work councils, as in many German companies), workers are consulted in technology and organizational decisions, and they have at times been successful in acting as a counterweight to excessive automation.

In their heyday, labor unions succeeded because they formed bonds among their members. They provided camaraderie for people working together and on similar tasks. They were a nexus of cooperation along common economic interests, centered on better working conditions and higher wages. And they cultivated political objectives aligned with their membership's beliefs and interests, such as the right to vote. These ingredients are unlikely  to work as synergistically today.

Workplaces have become much less concentrated and more  diverse, so camaraderie is harder to achieve. With the rise of more highly educated and white-collar employees in most workplaces, economic interests among workers are more divergent as well. Blue-collar production workers are now a smaller fraction of the US labor force (about 13.7 percent as of 2016), and organizational forms centered on them are unlikely to speak for the entire workforce. There are also fewer common-interest political aims within the working population, which is now more divided between  Right and Left than was the case half a century ago.

Nevertheless, new methods for organizing workers may succeed where older approaches have failed, and some of this can already be seen in successful unionization drives in companies such as Amazon and Starbucks in 2021-2022. The worker initiated union election of Amazon's Staten Island warehouse used very different tactics to succeed in an environment unlike those where traditional labor movements once thrived. Turnover rates were enormous in the company's warehouses, and the workforce was diverse in every respect, coming from myriad backgrounds and speaking dozens of different languages. The movement was organized by workers on the shop floor, not by professional union personnel. It funded itself over the social media platform GoFundMe rather than receiving centralized union money. It appears to have succeeded by developing a less rigid and less ideological approach, focusing on issues relevant to most Amazon warehouse employees, such as excessive monitoring, insufficient  breaks, and high injury rates. Although its strategy is very different from the iconic "sit-down strike" of GM workers in 1936, which was a turning point for the US labor movement, it is reminiscent in terms of developing new methods of organizing from the ground up.

The other problem with labor unions in the United States and  Britain is, as we have seen, their traditional structure is organized at the level of individual plants, which breeds a more conflictual relationship with management. More broad-based organizations, rather than just at the level of plants or firms, will be necessary  moving into the future. These may take the form of multilayer organizations, whereby some decisions are taken at the workplace level and others are made at the industry level. The dual-track German system is a relevant example: work councils are engaged in communication and coordination in workplaces and can have a say in technology and training decisions, whereas industry  unions are more focused on wage setting. Of course, it is possible that future labor movements may end up looking more like other civil-society organizations or more loosely associated industry-level confederations. This suggests that experimenting with new organizational forms is an important step moving forward.

### Civil-Society Action, Alone and Together

The West is now a consumer society, and consumer preferences and action are important levers for influencing companies and technologies. Consumer reaction was vital in the case of renewable energy and electric cars. It was also pressure from consumers, together with media coverage, that forced YouTube and Reddit to take some steps to limit extremism on their platforms.

However, collective action requires a large group of people  acting together to achieve an objective—for example, pushing companies toward reducing their carbon footprint. Such action is costly for most people, who will have to spend time to become informed, to attend meetings, to change their consumption habits, and to occasionally go out and protest. These costs multiply when there is a counterpush from companies and sometimes, even worse, from state security services. In authoritarian and even  semi-democratic regimes, authorities can damp down on protests and civil-society organizations.

These dynamics produce the **"free-rider" problem**^[The "free-rider" problem is... for the purposes of this class, structurally equivalent to the Fisher's Dilemma (You can think of it like, free-rider problem is Fisher's Dilemma for $N$ rather than 2 players)]: people who share the same values may nevertheless be tempted not to take part in collective action in order to avoid paying the costs. This tendency of course intensifies when punishments against dissidents increase. For example, recent research on Hong Kong protests shows that when pro-democracy university students expect others to take part in rallies against antidemocratic measures, they themselves become less likely to join the protests, free riding on others' efforts. Free riding is at the root of the **collective-action dilemma**: without coordination, only a minority of people who desire social change take part in collective action.

Consumer choice, the ultimate uncoordinated, individual  action, suffers mightily from the collective-action dilemma. Only a fraction of those who want to reduce carbon emissions will give up air travel or fossil-fuel energy, for example. Civil-society organizations that coordinate consumers and make them act more as citizens rather than individual decision makers in the marketplace are vital.

In addition to providing a forum for debate and trusted information dissemination, civil-society organizations can create both carrots and sticks to coordinate protests and public **pressure on misbehaving companies**. On the carrot side, they cultivate an ethos for taking part in activities that are good for the public interest and additionally develop links between different people, who then encourage one another to participate. For sticks, they can sometimes shame individuals for free riding on the efforts of others.

Although other organizations, such as labor unions, can also play these roles, civil-society organizations are important, especially when the main issues, such as climate change or digital technologies, have effects on large numbers of people and cut across traditional groups. For instance, although labor unions can contribute to climate-change activism and mitigation, they are not ideally situated to solve climate-related collective-action problems, compared to, say, Greenpeace or 350.org, which can organize people from different walks of life and backgrounds. The same considerations apply to action on digital technologies and business regulation. In both cases, the effects are wide-ranging, necessitating broad coalitions that can best be constructed by civil-society organizations.

Can online organizations help rather than hinder these  efforts? Is broad-based civil society even possible in the digital age? Although the optimism of the early 2000s about social media and the internet providing a forum for a digital "public sphere" has been dashed, new and better online communities can be built.

Periodic elections to select representatives are not the only aspect of democratic politics. Self-governance, both at workplaces and more broadly, may be as important as elections. Indeed, successful democratic periods in the West often coincide with other institutional vehicles for people to participate in political decision making, express and develop their opinions, and pressure public  policy. These include local politics, town hall-type arrangements, and most importantly various civil-society clubs and organizations.

Meanwhile, in some non-Western societies, bottom-up political participation has taken place without such elections—for instance, in the context of village councils and the election of traditional chiefs in parts of sub-Saharan Africa. Among others, this type of partic  ipation (via traditional assemblies called *kgotla*) played a defining role in the economic and political development of Botswana, one of the most economically successful countries of the last fifty years.

Pathways for democratic institutions to cultivate new and better online communities are critical. There are some digital technologies that can play a helpful role rather than a harmful one, and finding ways to encourage their development is crucial. For example, digital tools are well suited for creating new forums in which debate and exchange of opinions can be carried out in real time and within a prespecified set of rules. Online meetings and  communication can reduce participation costs, enabling larger-scale cross-cutting associations. Digital tools can also ensure that even in large meetings, individuals can participate in debate by making comments or recording their approval or disapproval. If these tools are well designed, they can help empower and amplify diverse voices—an imperative for successful democratic governance. Efforts in this direction include the `New_Public` project, founded by internet activist Eli Pariser and Professor Talia Stroud, which seeks to develop a platform and tools for deliberation and bottom-up participation, especially on issues relevant to the future of technology. The project advocates a richer view of technology as "what we can learn to do" (as articulated by the science-fiction writer Ursula Le Guin) and calls for a more decentralized approach to its development.

The new democracy initiative led by Audrey Tang, a former  activist and currently the digital minister of Taiwan, is particularly noteworthy. Tang entered politics as part of the student-led Sunflower Movement, which occupied the Taiwanese Parliament to protest against the 2013 trade deal with China that was being signed by the ruling Kuomintang Party without sufficient public review or consultation.

Tang, previously a software entrepreneur and programmer,  volunteered to help the movement communicate its message to the broader public. After the Democratic Progressive Party came  to power in the 2016 general election, Tang was appointed as a  minister, with a focus on digital communication and transparency. She has built a variety of digital tools for providing transparency in government decision making and for increasing deliberation and consultation with the public. This digital-democracy  approach was used for a number of key decisions, including the regulation of the ride-sharing platform Uber and of liquor sales. It involves a "presidential hackathon," which allows citizens to make proposals to the executive. Another platform, `g0v`, provides  open data from several Taiwanese ministries, which civic hackers can use to develop alternative versions of bureaucratic services.  These technologies helped Taiwan's early and effective response to COVID-19, in which the private sector and civil society collaborated with the government to develop tools for testing and contact tracing.

New forums for virtual participation can of course repeat  the same mistakes that social media commits today, exacerbating echo chambers and extremism. Once such tools start being used extensively, some parties will come up with strategies to spread disinformation, whereas others might use such platforms for demagoguery. Sensational, misleading content may start spreading, and rival viewpoints can begin shouting each other down rather than deliberating constructively. The best way of avoiding  such mistakes is to view pro-democratic online tools as a work in progress that needs to be updated continuously as new challenges develop, and also as a complement, rather than as a full substitute, to traditional, in-person civic engagement.

These solutions have a technical aspect as well as a social dimension. The algorithmic architecture of online systems can be designed to aid deliberation and dialogue, instead of attention grabbing and provocation. Because algorithms need to come from the private sector, improved market incentives for technology development remain critical, as we discuss next.

Civil-society action also depends on information on deals and decisions in the corridors of power. Digital technologies can help shed light on the influence of large corporations and corporate money in politics. Online tools can track links and flows of money and favors between companies and politicians and bureaucrats. We certainly do not agree with former US Supreme Court justice Anthony Kennedy's excessively optimistic outlook: "With the advent of the Internet, prompt disclosure of expenditures can  provide shareholders and citizens with the information needed to hold corporations and elected officials accountable for their positions and supporters." This can happen only when there are other traditional safeguards. Ensuring transparency should thus be viewed as complementary to more traditional types of civil-society action. For example, it could take the form of **automatic  detection and public posting of all meetings and interactions of politicians and top bureaucrats with lobbies and private-sector managers**.

It is important to strike the right balance in transparency. The public does not need to be informed about every policy debate and all the negotiations that politicians undertake in order to build coalitions. However, with the amount spent on lobbying in the Western world reaching astronomical levels, the public has a  right to know about deals reached by lobbyists, politicians, and firms, and these connections need to be regulated.

## Policies for Redirecting Technology (pg. 402)

The existence of countervailing powers and even new institutions by themselves will not redirect technology. Specific policies that **change incentives**^[Think of the Pigou tax, and how it changes incentives by exactly the amount needed to "transform" a Prisoner's Dilemma into an Invisible Hand Game!] and encourage socially beneficial innovations are necessary. Complementary policies—including subsidies and support for more worker-friendly technologies, tax reform, worker-training programs, data-ownership and data-protection schemes, breaking up of tech giants, and digital advertisement  taxes—can help initiate a major redirection of technology.

### Market Incentives for Redirection

Government subsidies for developing more socially beneficial technologies are one of the most powerful means of redirecting technology in a market economy. Subsidies are more potent when they are bolstered by changes in social norms and consumer preferences that push in the same direction, as demonstrated by our experience with  renewable energy.

There are important differences between green and digital  technologies, however. When environmental concerns first surfaced, activists did not have a full understanding of how energy consumption was affecting climate or of how the carbon content of energy could be consistently measured. All the same, the scientific understanding and the measurement framework developed rapidly and were in place as early as the 1980s. It then became straightforward to estimate how much greenhouse gases different energy sources were emitting. This knowledge now underpins most carbon taxes, cap-and-trade schemes, and subsidies for  renewable energy and electric cars.

Determining how different digital technologies are used and their impact on wages, inequality, and surveillance is much harder. For example, new digital technologies that enable managers to more efficiently track the performance of their subordinates could be viewed as human complementary, for they are enabling managers to do new tasks and expand their capabilities. Simultaneously, they may intensify surveillance or eliminate tasks that used to be performed by other white-collar workers.

Nevertheless, there are a number of principles useful for creating a framework for measuring the impact of digital technology. First, whether new technologies are **used for monitoring and surveillance** is fairly straightforward to ascertain. Both the development and deployment of these technologies should be discouraged. **A government agency such as OSHA could develop clear guidelines** that prevent the most intrusive forms of surveillance and data collection on employees, and other agencies could  similarly regulate data collection on consumers and citizens. As an additional step, the federal government could also **decide not to enforce** patents on technologies that are **aimed at worker or citizen surveillance**—including those filed in China. Conversely, technologies that provide tools for worker and user **privacy** can also be **identified and subsidized**.

Second, there is a telltale sign of automation technologies: reducing the labor share of value added, meaning that once these technologies are introduced, **how much of value added goes to capital increases and how much gets captured by labor decreases**^[Relative to course topics, here you can think of the different points we've identified where **power differentials** (like the $\mathcal{P}_i > \mathcal{P}_j$ portion of the Pareto Frontier in the Fishers' Dilemma) skew outcomes away from socially-optimal outcomes and towards unfair outcomes.]. Existing research documents that the introduction of robots and other automation technologies almost always leads to significantly lower labor share. Likewise, technologies that create new tasks for workers tend to increase the labor share. On this basis, **technologies that raise the labor share can be encouraged via subsidies for their use and their development**. Such policies can be also useful in encouraging the sharing of productivity gains with workers because higher wage raises would increase the labor share and thus qualify companies for additional subsidies.

Third, subsidies for research directions that are human complementary can be provided on the basis of more detailed data about whether new methods are complementing humans or automating work when used in practice. We have already mentioned several examples where new digital technologies can complement humans by creating new tasks—for example, by providing better information for personalized teaching or health care, or by enabling improved design and production work on shop floors with the help of augmented- and virtual-reality capabilities.  Although such a classification may be much easier after technologies are deployed, some of this information is available at the development stage and could be a first step toward a **measurement framework for the extent of automation of new technologies**. This measurement framework could then be used for providing **subsidies to certain lines of innovation**.

Some amount of ambiguity in the exact purpose and application of new technologies is not a major problem: preventing automation is not the objective. What policy makers should strive for is cultivating a plurality of approaches to encourage a greater focus on human-complementary and human-empowering technologies. This goal does not require a perfect metric for classifying whether a technology will automate work or create new tasks for workers. Rather, it requires a commitment to experiment with new technologies that try to help workers and citizens.

For the same reasons, we do not support automation taxes  aimed at directly discouraging the development and adoption of automation technologies. Redirection should target a more balanced technology portfolio, and subsidies to new human-complementary technologies can achieve this more effectively. Moreover, given the difficulty of distinguishing automation from other uses of digital technologies, automation taxes are currently not practical. Just taxing the clear examples of automation technologies, such as industrial robots, would not be optimal either, for such a policy would leave out the **much more pervasive algorithmic automation technologies**. Nevertheless, if subsidies and other policies cannot succeed in redirecting technological efforts, automation taxes may need to be considered in the future.

### Breaking Up Big Tech

Big businesses have become too powerful, and that is a problem in and of itself. Google dominates search, Facebook has few rivals in social networking, and Amazon  is developing a lock on e-commerce. These overwhelming market shares remind us of Standard Oil, which had a 90 percent market share of oil and oil products when it was broken up in 1911, and AT&T, which had a near monopoly on telephone service when it was broken up in 1982.

High levels of market concentration and gargantuan monopolies can choke off innovation and distort its direction. For example, Netscape Navigator created a much better product than Microsoft's browser in the mid-1990s and altered the direction of browsers by spurring a series of follow-on innovations by other companies (it was selected as "the best tech product of all time" by *PC Magazine* in 2007). Unfortunately, Netscape ended up being **crushed by Microsoft, despite a Department of Justice  antitrust case**.

These considerations may be more important today because  a handful of companies are dominating the direction of digital technologies and especially AI. Their business models and priorities focus on automation and data collection. Hence, breaking up the largest tech giants to reduce their dominance and create room for greater diversity of innovations is an important part of  redirecting technology.

Breakup by itself is not sufficient because it will not redi  rect technology away from automation, surveillance, or digital advertising. Take Facebook, which would likely be the first target of such antitrust action, owing to its controversial acquisitions of WhatsApp and Instagram. If the company were broken up and these two apps were separated from Facebook, data sharing between them would cease, but their business models would remain intact. Facebook itself would continue to seek the attention of its users and therefore continue to be a platform for the  **exploitation of insecurities, misinformation, and extremism**. WhatsApp and Instagram would also adopt the same business model, **unless pushed away from it by regulation or public pressure**. The same is likely true of YouTube, even if it were separated from Google's parent company, Alphabet.

Therefore, breakup and more broadly antitrust should be considered as a complementary tool to the more fundamental aim of redirecting technology away from automation, surveillance, data collection, and digital advertising.

### Tax Reform

The current tax system of many industrialized economies encourages automation. We saw in Chapter 8 that the US has taxed labor at an average rate of about 25 percent over  the last four decades because of payroll and federal income taxes, while imposing much lower taxes on equipment and software capital. Moreover, taxes on these types of investments have fallen steadily since 2000 because of the broader reductions in corporate income taxes and federal income taxes on high earners, and **increasingly generous allowances to write off tax obligations when firms invest in machinery and software**^[On this, think of the (very) brief break during lecture where I brought up @pistor_code_2019.].

A company investing in automation equipment or software  today pays a tax of less than 5 percent—fully 20 percentage points lower than the taxes it faces when it hires workers to perform the same tasks. Specifically, what this means is that when a company hires more workers and pays them $100,000 per year, it and the workers will jointly owe $25,000 in payroll taxes. When it instead  buys new equipment costing $100,000 to perform the same tasks, it pays less than $5,000 in taxes. This asymmetry is an impetus to additional automation and is present in similar forms, even if sometimes less pronounced, in the tax codes of several other Western economies.

Tax reform can remove this asymmetry and thus the incentives for excessive automation. A first step to achieve this would be to significantly reduce or even fully eliminate payroll taxes. The last thing we want today is to make it more expensive for people to work.

A second step would be a modest increase in taxes on capital. Eliminating provisions that reduce the effective taxation of capital, such as generous depreciation allowances and the advantageous tax status of private equity and carried interest, would be one way of achieving this. Additionally, moderately higher corporate income taxes would directly increase the marginal tax rates  faced by capital owners, further closing the gap between the taxation of capital and labor. It is important to simultaneously close tax loopholes, including schemes that minimize tax liabilities of multinational corporations by shifting their accounting profits across jurisdictions; otherwise, corporate income taxes could be avoided and would not be fully effective.

### Investing in Workers

The tax incentives for investments in equipment and software are not available to companies when it comes to investments in workers. Equalizing the rates at which  capital and labor are taxed is an important step in removing the bias in favor of automation ahead of hiring and investing in workers.

But there is more that the tax code can do. Worker marginal productivity can be raised by post-schooling training. Even workers with college or post-college degrees learn most of the skills required for a given task or industry once they start working in a company. Some of these training investments take place in formal settings, such as vocational courses, whereas other relevant skills  are learned on the job, from senior coworkers and supervisors, a process that is often aided by how jobs are designed and how much time employees are allowed to allocate to training activities. We have seen that the training of low-education workers was an important pillar of shared prosperity before the 1980s.

There are good reasons why the level of training investment that companies choose may be insufficient. Much of what a worker learns via training is "general" in the sense that they could use their skills productively with other employers as well. Investing in general training is less attractive for firms because competition from other employers implies that they would have to pay higher  wages or may even lose the worker after training, without being able to recoup their investments. The Nobel Prize-winning economist Gary Becker pointed out how more efficient levels of training could be supported when workers indirectly pay for them by taking a pay cut during training, with the hope that they will be able to enjoy higher wages in the future. This solution is often imperfect, however. Workers may not be able to afford pay cuts and may not trust that firms would really devote enough care and time to training once they do take such cuts. Worse, when wages are negotiated, as they often are, neither the firm nor the worker receives the full returns from training investments, making it impossible even for pay cuts to support adequate levels of training.

Institutional solutions and government subsidies to training could rectify the resulting underinvestment problem. For example, the German apprenticeship system incentivizes firms to fund major training efforts. The programs in many industries last two, three, or sometimes even four years and are made feasible by the fact that workers develop close relations with their employer and  do not immediately leave after apprenticeship. These schemes are often supported and supervised by labor unions. Similar apprenticeship programs exist in other countries but would be difficult to institute in the US and the UK, where unions are unlikely to play the same role and where quit rates for younger workers are much higher than in Germany. Government subsidies—for example, allowing companies to deduct training investments from taxable profits—should therefore play a more important role in the United States.

### Government Leadership to Redirect Technological Change

The government is not the engine of innovation, yet it can play a central role in redirecting technological change through taxes, subsidies, regulation, and agenda setting. Indeed, in many frontier research areas, the identification of specific need, combined with government leadership, has been critical because it focuses the attention of researchers on specifying attainable goals or aspirations.

That was certainly the case with antibiotics, one of the most transformative technologies of the twentieth century. The importance of drugs that could fight bacteria was already well understood when Alexander Fleming serendipitously discovered the bacteria-killing properties of penicillin at St. Mary's Hospital in London in 1928. Ernst Chain, Howard Florey, and later other chemists built on Fleming's breakthrough to purify and produce penicillin that could be administered to patients. As important as  the scientific advances, however, was the demand from the military, especially the US Army. The first successful application of the drug during World War II came in 1942. By D-Day on June 6, 1944, the US military had already procured 2.3 million doses of penicillin. Remarkably, **financial incentives played relatively little role in this discovery and development process**.

The same combination was important for many postwar scientific breakthroughs where the US government had articulated a strategic need, including for air defense, sensors, satellites, and computers. The recipe often brought together leading scientists to work on the problem and subsequently generated a sizable demand for these technologies, encouraging the private sector to jump in. A variant of this approach led to rapid vaccine development during the COVID-19 pandemic.

A similar combination could be effective in redirecting digital technology. When the social value of new research directions is established, it can draw many researchers in. Guaranteed demand for successful technologies can additionally incentivize private companies. For instance, the US government could convene and fund research teams to develop digital technologies that complement human skills to be used in education and health care, and commit to deploying them in US schools and Veterans Administration hospitals, provided that they meet the requisite technical standards.

This is not, we hasten to point out, traditional "industrial policy," which involves bureaucrats attempting to pick winners, either in terms of companies or specific technologies. Industrial policy's track record is mixed. When it succeeded, it took the form of government inducement for broad sectors, such as the chemical,  metal, and machine-tool industries of South Korea in the 1970s **or the metal industry of Finland between 1944 and 1952 (because of the in-kind war reparations that the country had to pay to the Soviet Union)**^[If reparations are someday paid to victims by present-day war-crime-doing countries, perhaps we could see an effect like this as well!].

Instead of picking winners, redirecting technology is much more about identifying classes of technologies that have more socially beneficial consequences. In the energy sector, for example, technological redirection requires support for green technologies overall rather than attempts to determine whether wind or solar, let alone what type of photovoltaic panel, is more promising. The type of government leadership we advocate builds on the same approach and seeks to encourage the development of  technologies that are more complementary to workers and citizen empowerment rather than trying to select specific technological trajectories.

### Privacy Protection and Data Ownership

Controlling and redirecting the technology of the future is in large part about AI, and AI is mostly about incessant data collection from everyone. Two proposals in this realm are worth discussing.

The first is strengthening the protection of user privacy. Massive data collection about users and their friends and contacts has a variety of adverse effects. Platforms harvest these data to manipulate users (which is of course a core part of their ad-based business model). Such data collection also opens the way to nefarious collaboration between platforms and governments wishing to snoop on citizens. Relatedly, so much data in the hands of a few platforms cultivates an **imbalance of power**^[👀] between them  and their competitors and users.

Stronger privacy protection, requiring platforms to get  explicit approval from users on what data they will collect and how they will use it, could be useful. But attempts to implement it—for example, with the European Union's **General Data Protection Regulation (GDPR)** in 2018—have not been very successful. Many users are not privacy conscious, even when prompted, because they do not understand how data will be utilized against them. Evidence suggests that GDPR **disadvantaged smaller companies**^[👀] but was not effective in circumventing data collection and surveillance by large companies, such as Google, Facebook, and Microsoft.

There is another fundamental reason why privacy protection is difficult: platforms obtain information from users about others, either because they are **indirectly revealing information about their friends** or because they enable the platform **to learn more about the specifics of their demographic groups**, which can be  used for **targeting ads or products to others with similar characteristics**. This type of **"data externality"**^[One last 👀] is often ignored by users.

A related idea, centered on providing **ownership rights** to users for their data, may be more effective than privacy regulations. Data ownership, originally proposed by the computer scientist Jaron Lanier, can simultaneously protect how user data are harvested and prevent large tech companies from corralling their data as a free input for their AI programs. It can also limit the ability of tech companies to **collect vast amounts of data from the web and public records without the consent of the people  involved**. Data ownership may even, directly or indirectly, discourage ad-based business models.

Part of the goal of data ownership is to ensure that users receive income from their data. However, for many applications, the **data of one user is highly substitutable with others' data**. For example, from the viewpoint of a platform, there are hundreds of thousands of users who can identify cute cats, and who does so is of no importance. This implies that platforms will have all the **bargaining power** against users and that even when user data are valuable, the platforms will be able to buy the data on the cheap. This problem is made worse in the presence of data externalities. Lanier recognizes this issue and advocates **"data unions,"** built on the model of the Writers Guild of America, which represents writers providing content for movies, television, and online  shows. Data unions can negotiate prices and terms for all users or subgroups, thus **circumventing "divide-and-conquer" strategies by platforms**, which could otherwise obtain data from one sub-group and then use the data for getting better terms from others^[HW3B, Q3 😉]. Data unions can also prevent tech giants from using the data that they have collected in one part of their business in order **to create an entry barrier in other activities**—such as Uber using data from its ride-sharing app to gain an advantage in food delivery (a  data-sharing practice that regulators in Vancouver recently tried to prevent).

Data unions could additionally provide models for other types of workplace organizations. They can become powerful civil-society associations and contribute to the emergence of a broader social movement, especially if combined with the other measures we are proposing

### Repeal Section 230 of the Communications Decency Act

Central to the regulation of the tech industry is Section 230 of the 1996 Communications Decency Act, which **protects internet platforms against legal action or regulation because of the content they host**. As Section 230 explicitly states, "No provider or user of an interactive computer service shall be treated as the publisher or speaker of any information provided by another information content provider." This passage has given protection to platforms such as Facebook and YouTube against accusations that they are featuring misinformation or even hate speech. This is often **supplemented by arguments of executives defending freedom of speech on their platform**. Mark Zuckerberg was quite categorical  on this in a Fox News interview in 2020: "I just believe strongly that Facebook shouldn't be the arbiter of truth of everything that people say online."

Under public pressure, tech platforms have recently taken  some steps to limit misinformation and extreme content. But they are unlikely to do much by themselves for a simple reason: **their business model thrives on controversial and sensational material**. This means that government regulation has to play a role, and a first step in this would be to repeal Section 230 and make platforms accountable when they *promote* such material.

The emphasis here is important. Even with much better monitoring, it would be unrealistic to expect that Facebook can eliminate all posts that include misinformation or hate speech. Yet it is not too much to expect that their algorithms should not give such  material a much broader platform by **"boosting" it and actively recommending it to other users**, and this is what the repeal of Section 230 should target.

We should also add that such a relaxation of Section 230 protection would be most effective for platforms such as Facebook and YouTube that use algorithmic promotion of content, and is less relevant for other social media, such as Twitter, where direct promotion is less relevant. For Twitter, experimenting with different regulation strategies, requiring the monitoring of the most heavily subscribed accounts, may be necessary.

### Digital Advertising Tax

Even getting rid of Section 230 is not enough, however, because it leaves unchanged the **business model** of internet platforms. We advocate a nontrivial digital advertising tax to encourage alternative business models, such as those based on subscription, instead of the currently prevailing model that largely relies on individualized targeted digital advertising. Some  companies, such as YouTube, have taken some (albeit halfhearted) steps in that direction. But currently, without a digital ad tax, a subscription-based system is not as profitable. **Since digital ads are the most important source of revenues from data collection and the surveillance of consumers**, a change of business model can be a powerful tool to redirect technology as well.

Advertisement in general has an important element of an  "arms race." Although some advertisements introduce consumers to brands or products they may not be aware of, expanding  their choices, much of it simply tries to make their product more appealing than their competitors'. Coca-Cola advertises not to  make consumers aware of its brand (it is safe to assume that everybody, at least in the United States, knows of Coca-Cola) but to convince them to buy Coke instead of Pepsi. Pepsi then responds by increasing its own advertisements. For arms race-type activities, when costs decline or potential impact increases, more  wastefulness may follow. Digital advertising has taken us into this territory by individualizing ads and increasing their impact while  also reducing the cost of advertisements to businesses. This bolsters the economic case for a digital advertisement tax.

Although we do not currently know how high such digital  taxes need to be in order to have a meaningful impact on massively profitable business models, we suspect that they have to be significant. Recall that the point of such taxes is not to raise revenues or have a small influence on the volume of advertisement but to alter the business model of online platforms. In any case, **some amount of policy experimentation will probably be needed**^[Here think of the **policy diffusion** topic we mentioned in class: for example, the map showing how California was the first state to "experiment" with data breach notification laws, which were then adopted by most other states in subsequent years.] to determine and set the right level of taxes.

Misinformation and manipulation are present off-line as  well—for example, on Fox News. Although there may be reasons for extending advertisement taxes to TV, there is a big difference from online platforms: TV channels do not have access to the technology for individualized digital advertisements and do not collect and then use vast amounts of data about the audience.

## Other Useful Policies

Policies that do not directly redirect technology are less well suited  to the task at hand, but may still be worth considering, especially when they tackle the large **inequalities** and the **excessive political power** of companies and their bosses.

### Wealth Taxes

Wealth taxes, imposed on those above a certain wealth threshold, have started to gain traction over the last decade. For example, in 1989 President Mitterrand introduced a tax in France on wealth levels above €1.3 million, which was reduced in scope by President Macron in 2017. In the US, Bernie Sanders and Elizabeth Warren, who both ran for president in 2020, have proposed wealth taxes. Sanders's 2020 plan was to impose a 2 percent  wealth tax on households with wealth in excess of $50 million, rising gradually to 8 percent for those whose wealth exceeds $10 billion. Warren's most recent proposal is to impose a 2 percent wealth tax on households with wealth above $50 million and a 4 percent tax on those with wealth in excess of $1 billion. Given the vast fortunes that have been made over the last several decades,  coupled with the need for additional tax revenues for bolstering the social safety net and other investments (as we detail below), well-administered wealth taxes can raise valuable revenue.

Although wealth taxes would not directly contribute to redirecting technological change, they would be helpful to reduce the wealth gaps that exist in many industrialized nations today. For example, a 3 percent wealth tax would, over time, significantly eat into the fortunes of tech tycoons such as Jeff Bezos, Bill Gates, and Mark Zuckerberg. An important question is whether smaller  wealth gaps would also reduce their persuasion power. This would  depend on other broader social changes, not just their exact wealth.

Wealth taxes are also difficult to estimate, and taxing in this fashion will multiply trickeries aimed at hiding wealth in trusts and other complex vehicles, sometimes offshore. For this purpose, wealth taxes should be combined with **corporate income taxes, imposed directly on company profits, which are easier to assess and collect**^[Here think about times we've talked about the challenges and ethical concerns around **data elicitation**!]. At the very least, wealth taxes would have to be coupled with stronger international cooperation among tax authorities, including an overhaul of the rules for offshore tax havens and a concerted effort to close loopholes. Any wealth tax would also need to be embedded within the constraints imposed by the rule of law and democratic politics and clear constitutional guidelines  to assuage concerns that such taxes could be used for expropriating certain groups.

On balance, we believe that wealth taxes, if coupled with significant efforts to close tax loopholes and change the accounting industry, could have benefits but are not a major part of the more systemic solutions we are seeking.

### Redistribution and Strengthening the Social Safety Net

The US needs a better social safety net and better and more redistribution. Much evidence shows that social safety nets have gotten much weaker in the United States and Britain, and this deficiency contributes to poverty and reduced social mobility. Social mobility today is much lower in the US than in Western European countries.

For example, **85 percent of the income differences between families are eliminated within a generation in Denmark**, where children of poor parents tend to get richer. **The same number is only about 50 percent in the United States**. Bolstering the safety net and improving schools in less advantaged areas have become urgent needs. Such policies need to be supplemented with broader  redistributive measures.

Although robust redistribution and improved social safety  nets, by themselves, are not going to affect the direction of technology or reduce the power of large tech companies, they can be an effective tool in reducing large inequalities that have emerged in the United States and other industrialized nations.

One specific proposal, popularized by Andrew Yang's Democratic primary campaign in 2020, deserves discussion: universal basic income. UBI, which promises an unconditional dollar amount for every adult, has emerged as a popular policy idea in some left-wing circles, among more libertarian scholars such as Milton Friedman and Charles Murray, and with tech billionaires such as Amazon's Jeff Bezos. Support for the idea is rooted, in  part, in the clear inadequacies of the safety net in many countries, including the United States. But it also receives a powerful boost from the narrative that robots and AI are pushing us toward a jobless future. And so, the narrative goes, we need the UBI in order to provide income to most people (and **to prevent the pitchfork uprising that some tech billionaires are fearing**).

UBI is not ideal for bolstering the social safety net, however, because it transfers resources not just to those who need them but to everybody. In contrast, many of the programs that have formed the basis of twentieth-century welfare states around the world target transfers, including health spending and redistribution, to those in need. Because of this lack of targeting, UBI  would be more expensive and less effective than the alternative  proposals.

UBI is also likely the wrong type of solution to our current  predicament, especially compared to measures aimed at creating new opportunities for workers. There is considerable evidence suggesting that people are more satisfied and are more engaged with their community when they feel that they are contributing value to society. In studies, people not only report improved psychological well-being when they work, compared to just receiving  transfers, but are even willing to forgo a considerable amount of money rather than give up work and accept pure transfers.

The more fundamental problem with UBI is not related to  psychological benefits of work but to the misguided narrative about the problems facing the world it propagates. UBI naturally lends itself to interpretations of our current predicament that are wrong and counterproductive. It **implies that we are inexorably  heading toward a world of little work for most people and growing inequality between the designers of more and more advanced digital technologies and the rest**, so major redistribution is **the only thing we can do**. In this way, it is also sometimes justified as the only way of quelling growing discontent in the population. As we have emphasized, this perspective is wrong. **We are heading toward greater inequality not inevitably** but **because of faulty choices about who has power in society and the direction of technology**. These are the fundamental issues to be addressed, whereas UBI is defeatist and accepts this fate.

In fact, UBI fully **buys into the vision of the business and tech elite that they are the enlightened, talented people who should generously finance the rest**. In this way, it pacifies the rest of the population and amplifies the status differences. Put differently, rather than **addressing the emerging two-tiered nature of our society**, it reaffirms these artificial divisions.

This all suggests that rather than search for fanciful transfer mechanisms, society should strengthen its existing social safety nets and crucially attempt to combine this with the creation of meaningful, well-paying jobs for all demographic groups—which  means redirecting technology.

### Education

Most economists' and policy makers' favorite tool for combating inequality is more investment in education. There is some wisdom to this conventional wisdom: schools are critical for worker skills and contribute to society by inculcating its core values among the young. There is also a sense in which schooling is deficient in many nations, especially for students from low socioeconomic backgrounds. In addition, as we have seen, schools are one of the areas where human-complementary AI can be most  fruitfully deployed to improve outcomes and create meaningful new jobs. There are parts of the schooling system in the US, such as community colleges and vocational schools, that are due for a major revamp, particularly in order to focus more on skills that will be in greater demand in the future.

Although education by itself is not going to alter the trajectory of technology or reenergize countervailing powers, educational investments can help some of the most disadvantaged citizens who do not have access to good schooling opportunities.

Greater educational investments can help society produce  more engineers and computer programmers, who will have higher earnings as a result of their upgraded skills, but we have to bear in mind that there is a limit to how many of these positions will be demanded by companies. Education has an indirect beneficial effect as well, which can help the rest. When there are more engineers and computer programmers, this may increase the demand for other, lower-skill occupations, and less educated workers may also benefit—even if they are not the ones receiving the education and obtaining the coveted programming and engineering jobs. This transmission of prosperity is related to the productivity bandwagon and sometimes works in the hoped-for fashion, but its reach depends on the nature of technology and the extent of worker power. Hence, these indirect effects from education can be more significant when there is some redirection of technology  (so that not all lower-skill jobs are automated) and when institutions enable even lower-skill workers to bargain for decent wages.

Finally, we warn **against the view that technology should adjust in its own way and the only thing society can do to counter its adverse effects is to educate more of the workforce**. The direction of technology, its inequality implications, and **the extent to which productivity gains are shared between capital and labor are not inescapable givens; they are societal choices**. Once we accept this reality, the case that society should let technology go wherever powerful corporations and a small group of people want, then do its best by trying to catch up with education, seems less compelling. Rather, technology should be steered in a direction that best uses a workforce's skills, and education should of course  simultaneously adapt to new skill requirements.

### Minimum Wages

Minimum-wage floors can be a useful tool for economies where low-wage jobs are a persistent problem, as in the United States and the United Kingdom. Many economists  once opposed minimum wages because of the fear that they would reduce employment: higher wage costs would discourage firms from hiring. The consensus among economists has been shifting, for evidence from many Western labor markets has indicated that moderate-level minimum wages do not reduce employment significantly. In the US the current federal minimum wage is $7.25 per hour, which is very low, especially for workers in urban areas.  In fact, many states and cities have their own higher minimum wages. For instance, Massachusetts currently has a minimum wage of $14.25 for employees who do not receive tips.

The evidence also indicates that minimum wages reduce  inequality because they increase wages for workers in the bottom quarter of the wage distribution. Modest increases in the federal minimum wage in the United States (for example, in line with the proposals to gradually raise it to $15 per hour) and similar increases in wage floors in other Western nations will be socially beneficial, and we support them.

Nevertheless, minimum-wage hikes are not a systemic solution to our problems. First, minimum wages have their biggest impact on the lowest-paid workers, whereas reducing overall inequality necessitates sharing productivity gains more equitably throughout the population. Second, minimum wages can have only a small  role in countering the excessive power of big business and labor markets.

Most importantly, if the direction of technology remains distorted toward automation, higher minimum wages may backfire. As evidence from the COVID pandemic shows, **when workers are not available to take jobs at relatively low wages in the hospitality and service sectors, companies have a powerful incentive to automate work**. Hence, in the age of automation, minimum wages can have unintended consequences—unless accompanied by a broader redirection of technology.

This motivates our perspective that the minimum wage is  most useful as part ofa broader package aimed at redirecting technology away from automation. If technology can become more worker friendly, businesses would be less tempted to automate work as soon as they face higher wages. In such a scenario, when faced by higher wages, employers may also choose to invest in worker productivity—for example, with training or technological  adjustments. This reiterates our overall conclusion that redirecting technological change and making corporations view workers as an important resource is critical. If this can be achieved, minimum wages can be more effective and less likely to backfire.

### Reform of Academia

Last but not least is need for reform in academia. Technology depends on vision, and vision is rooted in  **social power**, which is largely about **convincing the public and decision makers of the virtues of a particular path of technology**. Academia plays a central role in the cultivation and exercise of this type of social power because universities build the perspectives, interests, and skills of millions of talented young people who will  work in the technology sector. In addition, top academics often work with leading tech firms and also directly influence public opinion. We would therefore benefit from a more independent academia. Over the last four decades, academics in the United States and other countries have started losing this independence because the amount of corporate money has skyrocketed. For example, **many academics in computer science, engineering, statistics, economics, and physics departments—and, of course,  business schools—in leading universities receive grants and consulting engagements from tech companies**.

We believe that it is imperative to require greater transparency of such funding relationships and potentially **establish some limits** to restore greater independence and autonomy to academia  More government funding for basic research would also remove the dependence of academics on corporate sponsors. Nevertheless, obviously, academic reform will not redirect technology by itself and should be viewed as a complementary policy lever.

## The Future Path of Technology Remains to Be Written

The reforms we have outlined are a tall order. The tech industry and large corporations are politically more influential today than they have been for much of the last hundred years. Despite scandals, tech titans are respected and socially influential, and they are rarely questioned about the future of technology—and the type of "progress"—they are imposing on the rest of society. A social movement to redirect technological change away from automation and surveillance is certainly not just around the corner.

All the same, we still think the path of technology remains unwritten.
